name: Comments
on:
  push:
    branches:
      - master

jobs:
  comments:
    name: Comments
    runs-on: ubuntu-latest
    steps:
      - name: Comment on commit
        uses: Discord-Datamining/comments-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}