name: Comments
on:
  push:
    branches:
      - master

jobs:
  comments:
    name: Comments
    runs-on: ubuntu-latest
    steps:
      - name: Comment on commit
        uses: xHyroM/discord-assets/.github/actions/comments@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}