name: Mine Domains
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  mine:
    name: Mine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: 19
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - name: "Run script"
        run: |
          git config --global url.https://${{ secrets.ACCESS_TOKEN }}@github.com/.insteadOf https://github.com/
          git config user.name "xHyroM"
          git config user.email "github@xhyrom.dev"
          pnpm install
          pnpm run start --filter=scripts -- domains
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_WEBHOOK_MISCELLANEOUS: ${{ secrets.DISCORD_WEBHOOK_MISCELLANEOUS }}
          SECURITYTRAILS_API_KEY: ${{ secrets.SECURITYTRAILS_API_KEY }}
