name: Mine
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup git
        run: |
          git config user.name "hyros-dataminer[bot]"
          git config user.email "154810797+hyros-dataminer[bot]@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Install dependencies
        run: pnpm i

      - name: Run
        run: pnpm run start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

          DISCORD_WEBHOOK_BUILDS: ${{ secrets.DISCORD_WEBHOOK_BUILDS }}
          WUMPUSCENTRAL_DISCORD_WEBHOOK_BUILDS: ${{ secrets.WUMPUSCENTRAL_DISCORD_WEBHOOK_BUILDS }} # builds but for wumpuscentral
          DISCORDINSIDERS_DISCORD_WEBHOOK_BUILDS: ${{ secrets.DISCORDINSIDERS_DISCORD_WEBHOOK_BUILDS }} # builds but for discord insiders

          DISCORD_WEBHOOK_HOST_BUILDS: ${{ secrets.DISCORD_WEBHOOK_HOST_BUILDS }}

          DISCORD_WEBHOOK_ROUTES: ${{ secrets.DISCORD_WEBHOOK_ROUTES }}
          DISCORDINSIDERS_DISCORD_WEBHOOK_ROUTES: ${{ secrets.DISCORDINSIDERS_DISCORD_WEBHOOK_LOCAL }} # routes but for discord insiders

          DISCORD_WEBHOOK_STRINGS: ${{ secrets.DISCORD_WEBHOOK_STRINGS }}
          DISCORDINSIDERS_DISCORD_WEBHOOK_STRINGS: ${{ secrets.DISCORDINSIDERS_DISCORD_WEBHOOK_STRINGS }} # strings but for discord insiders

          DISCORD_WEBHOOK_STYLESHEETS: ${{ secrets.DISCORD_WEBHOOK_STYLESHEET }} # todo: change to STYLESHEETS
          DISCORDINSIDERS_DISCORD_WEBHOOK_STYLESHEETS: ${{ secrets.DISCORDINSIDERS_DISCORD_WEBHOOK_LOCAL }} # stylesheets but for discord insiders

          DISCORD_WEBHOOK_EXPERIMENTS: ${{ secrets.DISCORD_WEBHOOK_EXPERIMENTS }}
          WUMPUSCENTRAL_DISCORD_WEBHOOK_EXPERIMENTS: ${{ secrets.WUMPUSCENTRAL_DISCORD_WEBHOOK_EXPERIMENTS }} # experiments but for wumpuscentral
          DISCORDINSIDERS_DISCORD_WEBHOOK_EXPERIMENTS: ${{ secrets.DISCORDINSIDERS_DISCORD_WEBHOOK_EXPERIMENTS }} # experiments but for discord insiders

          DISCORD_WEBHOOK_POSTS: ${{ secrets.DISCORD_WEBHOOK_POSTS }}
          DISCORDINSIDERS_DISCORD_WEBHOOK_POSTS: ${{ secrets.DISCORDINSIDERS_DISCORD_WEBHOOK_LOCAL }} # posts but for discord insiders
          WUMPUSCENTRAL_DISCORD_WEBHOOK_POSTS: ${{ secrets.WUMPUSCENTRAL_DISCORD_WEBHOOK_POSTS }} # posts but for wumpuscentral

          DISCORD_WEBHOOK_MISCELLANEOUS: ${{ secrets.DISCORD_WEBHOOK_MISCELLANEOUS }}
          DISCORDINSIDERS_DISCORD_WEBHOOK_MISCELLANEOUS: ${{ secrets.DISCORDINSIDERS_DISCORD_WEBHOOK_MISCELLANEOUS }} # miscellaneous but for discord insiders

          SCRAPE_DOMAINS: false
          SCRAPE_GITHUB: false
          SCRAPE_POSTS: true
          SCRAPE_CLIENT: true
