name: Mine Comments
on:
  push:
    branches:
      - "**"
    paths:
      - "data/*"
      - "data/**"

jobs:
  comments:
    name: Add comments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - name: "Run script"
        run: |
          pnpm install
          pnpm run start --filter=scripts -- diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          DISCORD_WEBHOOK_STRINGS: ${{ secrets.DISCORD_WEBHOOK_STRINGS }}
          DISCORD_WEBHOOK_ROUTES: ${{ secrets.DISCORD_WEBHOOK_ROUTES }}
          DISCORD_WEBHOOK_STYLESHEET: ${{ secrets.DISCORD_WEBHOOK_STYLESHEET }}
          DISCORD_WEBHOOK_BLOG_POSTS: ${{ secrets.DISCORD_WEBHOOK_BLOG_POSTS }}
          DISCORD_WEBHOOK_SUPPORT_ARTICLES: ${{ secrets.DISCORD_WEBHOOK_SUPPORT_ARTICLES }}
          DISCORD_WEBHOOK_SUPPORT_DEV_ARTICLES: ${{ secrets.DISCORD_WEBHOOK_SUPPORT_DEV_ARTICLES }}
          DISCORD_WEBHOOK_CREATOR_SUPPORT_ARTICLES: ${{ secrets.DISCORD_WEBHOOK_CREATOR_SUPPORT_ARTICLES }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
